# Generated by Django 4.2.2 on 2023-06-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Back", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networking",
            options={"verbose_name_plural": "Networking"},
        ),
    ]
