# Generated by Django 4.2.2 on 2023-06-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Back", "0004_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
