# Generated by Django 4.1.2 on 2023-06-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Back", "0005_contacts_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "About",
            },
        ),
        migrations.DeleteModel(
            name="Analysis",
        ),
        migrations.DeleteModel(
            name="Mentorship",
        ),
        migrations.DeleteModel(
            name="Networking",
        ),
        migrations.DeleteModel(
            name="PC",
        ),
        migrations.DeleteModel(
            name="Web",
        ),
        migrations.AlterModelOptions(
            name="home",
            options={"verbose_name_plural": "Home"},
        ),
        migrations.AlterField(
            model_name="home",
            name="bg_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
