# Generated by Django 4.1.2 on 2023-06-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Back", "0006_about_delete_analysis_delete_mentorship_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
